from setuptools import setup

setup(
    name='flasktry',
    version='',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.importlib', 'venv.Lib.collections',
              'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip.req', 'venv.Lib.site-packages.pip.vcs',
              'venv.Lib.site-packages.pip.utils', 'venv.Lib.site-packages.pip.compat',
              'venv.Lib.site-packages.pip.models', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip.commands', 'venv.Lib.site-packages.pip.operations',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.click', 'venv.Lib.site-packages.flask',
              'venv.Lib.site-packages.flask.ext', 'venv.Lib.site-packages.isapi', 'venv.Lib.site-packages.wheel',
              'venv.Lib.site-packages.wheel.tool', 'venv.Lib.site-packages.wheel.signatures',
              'venv.Lib.site-packages.docker', 'venv.Lib.site-packages.docker.api',
              'venv.Lib.site-packages.docker.types', 'venv.Lib.site-packages.docker.utils',
              'venv.Lib.site-packages.docker.models', 'venv.Lib.site-packages.docker.transport',
              'venv.Lib.site-packages.jinja2', 'venv.Lib.site-packages.certifi', 'venv.Lib.site-packages.chardet',
              'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.MySQLdb',
              'venv.Lib.site-packages.MySQLdb.constants', 'venv.Lib.site-packages.pymysql',
              'venv.Lib.site-packages.pymysql.tests', 'venv.Lib.site-packages.pymysql.tests.thirdparty',
              'venv.Lib.site-packages.pymysql.tests.thirdparty.test_MySQLdb',
              'venv.Lib.site-packages.pymysql.constants', 'venv.Lib.site-packages.urllib3',
              'venv.Lib.site-packages.urllib3.util', 'venv.Lib.site-packages.urllib3.contrib',
              'venv.Lib.site-packages.urllib3.contrib._securetransport', 'venv.Lib.site-packages.urllib3.packages',
              'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.adodbapi',
              'venv.Lib.site-packages.requests', 'venv.Lib.site-packages.werkzeug',
              'venv.Lib.site-packages.werkzeug.debug', 'venv.Lib.site-packages.werkzeug.contrib',
              'venv.Lib.site-packages.win32com', 'venv.Lib.site-packages.win32com.test',
              'venv.Lib.site-packages.win32com.demos', 'venv.Lib.site-packages.win32com.client',
              'venv.Lib.site-packages.win32com.makegw', 'venv.Lib.site-packages.win32com.server',
              'venv.Lib.site-packages.win32com.servers', 'venv.Lib.site-packages.pythonwin.pywin',
              'venv.Lib.site-packages.pythonwin.pywin.mfc', 'venv.Lib.site-packages.pythonwin.pywin.idle',
              'venv.Lib.site-packages.pythonwin.pywin.Demos.ocx', 'venv.Lib.site-packages.pythonwin.pywin.tools',
              'venv.Lib.site-packages.pythonwin.pywin.dialogs', 'venv.Lib.site-packages.pythonwin.pywin.docking',
              'venv.Lib.site-packages.pythonwin.pywin.debugger', 'venv.Lib.site-packages.pythonwin.pywin.framework',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor.color',
              'venv.Lib.site-packages.pythonwin.pywin.scintilla', 'venv.Lib.site-packages.websocket',
              'venv.Lib.site-packages.websocket.tests', 'venv.Lib.site-packages.markupsafe',
              'venv.Lib.site-packages.setuptools', 'venv.Lib.site-packages.setuptools.extern',
              'venv.Lib.site-packages.setuptools.command', 'venv.Lib.site-packages.win32comext.adsi',
              'venv.Lib.site-packages.win32comext.bits', 'venv.Lib.site-packages.win32comext.mapi',
              'venv.Lib.site-packages.win32comext.shell', 'venv.Lib.site-packages.win32comext.axdebug',
              'venv.Lib.site-packages.win32comext.ifilter', 'venv.Lib.site-packages.win32comext.propsys',
              'venv.Lib.site-packages.win32comext.axscript', 'venv.Lib.site-packages.win32comext.axscript.client',
              'venv.Lib.site-packages.win32comext.axscript.server', 'venv.Lib.site-packages.win32comext.internet',
              'venv.Lib.site-packages.win32comext.axcontrol', 'venv.Lib.site-packages.win32comext.directsound',
              'venv.Lib.site-packages.win32comext.directsound.test', 'venv.Lib.site-packages.win32comext.authorization',
              'venv.Lib.site-packages.win32comext.taskscheduler', 'venv.Lib.site-packages.dockerpycreds',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='Haneet',
    author_email='',
    description=''
)
